name: Crawler

on:
    schedule:
        # Runs "At minute 0 (every hour)." (see https://crontab.guru)
        - cron: "0 * * * *"
    workflow_dispatch:

jobs:
    crawler:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
              with:
                  ref: records
            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "16.x"
                  cache: "npm"
            - run: node ./dist/src/job.js
            - uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  commit_message: Update data
                  file_pattern: "*.csv"
